# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always


# Spring Configuration
spring:
  #to enable colors when you run your app outside intellij
  output:
    ansi:
      enabled: always

  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/taskflow_v1?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

  liquibase:
    enabled: true
    change-log: db/master.xml
  main:
    lazy-initialization: true

logging:
  file:
    name: taskFlow.log
  level:
    root: info


